version: "2.0"

networks: 
  basic:

services: 
  api:
    image: learn_api
    container_name: api
    ports: 
      - 8000:8000
    working_dir: /api
    command: yarn start
    networks: 
      - basic

  editor: 
    image: learn_editor
    container_name: editor
    tty: true
    ports: 
      - 3000:3000
    working_dir: /editor
    command: sh -c "yarn && yarn start && /bin/ash"
    networks: 
      - basic